# Sequential Task Execution Configuration - Simplified
# Essential configuration for the automated sequential workflow system

# Task Settings
task_settings:
  max_tasks_default: 10
  max_tasks_limit: 25
  branch_prefix: "sequential"
  auto_trigger_next_task: true

# PR Settings
pr_settings:
  labels:
    - "claude-generated"
    - "sequential-task"
    - "needs-review"
  enable_stacked_prs: true
  base_branch_strategy: "previous_task"
  title_format: "[Sequential] Task {task_number}: {task_title}"

# Claude Code Settings
claude:
  timeout_minutes: 30
  max_retries: 3
  retry_delay_seconds: 5

# GitHub Integration
github:
  respect_rate_limits: true
  squash_merge: true

# Security
security:
  validate_inputs: true
  max_input_length: 100000

# Performance
performance:
  workflow_timeout: 3600
  api_timeout: 300
  claude_timeout: 1800