name: Task Implementation to PR Automation

on:
  repository_dispatch:
    types: [implement-task]

jobs:
  implement-task:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Parse task data and update status
        id: parse-task
        uses: actions/github-script@v7
        with:
          script: |
            const path = require('path');
            const processTaskComment = require(path.join(process.cwd(), 'scripts', 'process-task-comment.js'));
            
            try {
              const result = await processTaskComment({ github, context });
              core.setOutput('task_data', JSON.stringify(result.taskData));
              core.setOutput('task_id', result.taskId);
              core.setOutput('comment_id', result.commentId);
            } catch (error) {
              console.log('❌ Task parsing failed:', error.message);
              core.setFailed(error.message);
            }

      - name: Implement task with Claude Code
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          custom_instructions: |
            Read CLAUDE.md and implement this task:

            Task: ${{ fromJson(steps.parse-task.outputs.task_data).title }}

            Description:
            ${{ fromJson(steps.parse-task.outputs.task_data).body }}

            Instructions:
            1. Implement the requirements completely
            2. Follow best practices and project conventions  
            3. Create/modify all necessary files
            4. Ensure code is production-ready
            5. Add appropriate error handling

      - name: Create PR and update task status
        uses: actions/github-script@v7
        with:
          script: |
            const path = require('path');
            const createPrFromTask = require(path.join(process.cwd(), 'scripts', 'create-pr-from-task.js'));
            
            // Get task data from previous step
            const taskData = JSON.parse('${{ steps.parse-task.outputs.task_data }}');
            const taskId = '${{ steps.parse-task.outputs.task_id }}';
            const commentId = '${{ steps.parse-task.outputs.comment_id }}';
            
            try {
              const prNumber = await createPrFromTask({ github, context, taskData, taskId, commentId });
              if (prNumber) {
                console.log(`✅ PR #${prNumber} created successfully`);
              } else {
                console.log('ℹ️ No PR created - no changes needed');
              }
            } catch (error) {
              console.log('❌ PR creation failed:', error.message);
              core.setFailed(error.message);
            }